//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyMVCProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReadingLog
    {
        public int Id { get; set; }
        public string ReaderName { get; set; }
        public Nullable<System.DateTime> ClockIn { get; set; }
        public Nullable<System.DateTime> ClockOut { get; set; }
        public string BookName { get; set; }
        public string Author { get; set; }
        public Nullable<int> ReaderId { get; set; }
    
        public virtual Reader Reader { get; set; }
    }
}
